### ISSUE TITLE
Cache the other A2S_* packets

### ISSUE THREAD

**Issue by aStonedPenguin** [danielga/gmsv_serversecure#6]
People like to use more than just A2S_INFO for DoS attacks

**Comment by danielga** [comment]
What kind of messages? Some require an active game session, others require a nonce that is returned after the first request. I doubt these kind of messages are used for DoS.

**Comment by aStonedPenguin** [comment]
A2S_GETCHALLENGE and A2S_PLAYER are the most common.

**Comment by danielga** [comment]
I wonder if I can just drop requests for A2S_SERVERQUERY_GETCHALLENGE since [it's deprecated and doesn't work at all in "newer games"](https://developer.valvesoftware.com/wiki/Server_queries#A2S_SERVERQUERY_GETCHALLENGE). About A2S_PLAYER, it requires a challenge, so you can't directly use it to create a denial of service (each time you attempt to A2S_PLAYER without the right nonce, the server will challenge you with a response that only contains the nonce and a tiny header). It doesn't seem very likely to be a candidate for DoS.

**Comment by uRandomAlex** [comment]
Can you just add an option to drop A2S_SERVERQUERY_GETCHALLENGE and A2S_PLAYER? I have noticed that some high-popular servers are doing that.

**Comment by VaasKahnGrim** [comment]
would be quite useful to cover the entirety of A2S_

**Comment by danielga** [comment]
I'm going to keep this module down to maintenance updates. I don't really feel like rewriting this code right now.
