### ISSUE TITLE
x64 bit Support?

### ISSUE THREAD

**Issue by Iydah** [danielga/gmsv_serversecure#82]
Will there ever be x64 server bit support?

**Comment by danielga** [comment]
We've been in this dance for multiple years. Facepunch doesn't seem willing to push forth with making the x86-64 branch the official Garry's Mod release. As such, I have no intentions of officially supporting it either, because I don't care about adding unnecessary workload to my already short free time for essentially what is repeated work between 2 branches. That said, you can try to build your own x86-64 releases, at your own risk, with no guaranteed support.
